"""
知识图谱数据模块
包含电路、模电、数电、高频电子线路、嵌入式等课程的知识点及其关联关系
大幅扩展版本：包含120+知识点和200+关系
"""

def get_knowledge_graph_data():
    """
    返回知识图谱的节点和边数据
    节点表示知识点，边表示知识点之间的关联关系
    ID范围：
    - 电路基础：1-99
    - 模拟电子：100-199
    - 数字电子：200-299
    - 高频电子：300-399
    - 嵌入式：400-499
    """
    nodes = [
        # ============ 电路基础课程 (ID: 1-99) ============
        {'id': 1, 'label': '电路基础', 'group': 'circuit', 'title': '电路基础理论', 'level': 0,
         'description': '电路基础是电子工程的核心课程，涵盖直流电路、交流电路、动态电路、磁路等基本理论和分析方法。为后续模拟电子、数字电子等课程奠定基础。',
         'difficulty': 1, 'learning_hours': 0},
        
        # 基础定律和定理
        {'id': 2, 'label': '欧姆定律', 'group': 'circuit', 'title': 'U=IR，基本电路定律', 'level': 1,
         'description': '欧姆定律是电学的基本定律之一，描述了电压、电流和电阻之间的关系。适用于线性电阻元件。',
         'difficulty': 1, 'learning_hours': 2,
         'formulas': ['U = I × R', 'I = U / R', 'R = U / I'],
         'keywords': ['电压', '电流', '电阻', '基本定律'],
         'prerequisites': [],
         'examples': ['计算串联电路总电阻', '计算并联电路总电流']},
        {'id': 3, 'label': '基尔霍夫定律', 'group': 'circuit', 'title': 'KCL和KVL，节点和回路分析', 'level': 1,
         'description': '基尔霍夫定律包括电流定律(KCL)和电压定律(KVL)，是电路分析的基础。KCL描述节点电流守恒，KVL描述回路电压守恒。',
         'difficulty': 2, 'learning_hours': 4,
         'formulas': ['ΣI_in = ΣI_out (KCL)', 'ΣU = 0 (KVL)'],
         'keywords': ['节点', '回路', '电流守恒', '电压守恒', '电路分析'],
         'prerequisites': [2],  # 需要先学欧姆定律
         'examples': ['节点电压法', '回路电流法', '支路电流法']},
        {'id': 4, 'label': '戴维南定理', 'group': 'circuit', 'title': '等效电压源定理', 'level': 2,
         'description': '戴维南定理指出，任何线性有源二端口网络都可以等效为一个电压源和一个电阻的串联。用于简化复杂电路的分析。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['U_oc = 开路电压', 'R_eq = 等效电阻', 'U = U_oc - I × R_eq'],
         'keywords': ['等效电路', '电压源', '线性网络', '电路简化'],
         'prerequisites': [2, 3],  # 需要先学欧姆定律和基尔霍夫定律
         'examples': ['计算含源网络的等效电路', '最大功率传输问题']},
        {'id': 5, 'label': '诺顿定理', 'group': 'circuit', 'title': '等效电流源定理', 'level': 2,
         'description': '诺顿定理指出，任何线性有源二端口网络都可以等效为一个电流源和一个电导的并联。与戴维南定理互为对偶关系。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['I_sc = 短路电流', 'G_eq = 等效电导', 'I = I_sc - U × G_eq']},
        {'id': 6, 'label': '叠加定理', 'group': 'circuit', 'title': '线性电路叠加原理', 'level': 2,
         'description': '叠加定理适用于线性电路，指出多个独立源共同作用时的响应等于各独立源单独作用时响应的代数和。',
         'difficulty': 2, 'learning_hours': 3,
         'formulas': ['U_total = ΣU_i', 'I_total = ΣI_i']},
        {'id': 7, 'label': '最大功率传输', 'group': 'circuit', 'title': '负载匹配原理', 'level': 2,
         'description': '最大功率传输定理指出，当负载电阻等于电源内阻时，负载获得最大功率。在通信和信号处理中有重要应用。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['R_L = R_S (匹配条件)', 'P_max = U_oc² / (4×R_S)']},
        {'id': 8, 'label': '特勒根定理', 'group': 'circuit', 'title': '功率守恒定理', 'level': 3,
         'description': '特勒根定理描述了电路中功率守恒关系，是电路理论中的基本定理之一，用于验证电路计算的正确性。',
         'difficulty': 4, 'learning_hours': 2,
         'formulas': ['ΣU_k × I_k = 0']},
        
        # 交流电路
        {'id': 10, 'label': '交流电路', 'group': 'circuit', 'title': '正弦交流电分析', 'level': 1,
         'description': '交流电路分析是电路理论的重要组成部分，研究正弦交流电在电路中的行为，包括阻抗、导纳、功率等概念。',
         'difficulty': 2, 'learning_hours': 4},
        {'id': 11, 'label': '阻抗', 'group': 'circuit', 'title': 'Z=R+jX，复数阻抗', 'level': 2,
         'description': '阻抗是交流电路中电压与电流的复数比，包含电阻和电抗两部分。阻抗的模表示大小，幅角表示相位关系。',
         'difficulty': 2, 'learning_hours': 3,
         'formulas': ['Z = R + jX', '|Z| = √(R² + X²)', 'φ = arctan(X/R)']},
        {'id': 12, 'label': '导纳', 'group': 'circuit', 'title': 'Y=G+jB，复数导纳', 'level': 2,
         'description': '导纳是阻抗的倒数，表示电路对交流电的导通能力。包含电导和电纳两部分，是并联电路分析的重要工具。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['Y = G + jB', 'Y = 1/Z', '|Y| = √(G² + B²)']},
        {'id': 13, 'label': '功率因数', 'group': 'circuit', 'title': 'cosφ，功率效率', 'level': 2,
         'description': '功率因数是衡量交流电路功率利用效率的重要参数，表示有功功率与视在功率的比值。功率因数越高，能量利用效率越高。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['cosφ = P / S', 'P = U×I×cosφ', 'Q = U×I×sinφ']},
        {'id': 14, 'label': '相量法', 'group': 'circuit', 'title': '复数表示法', 'level': 2,
         'description': '相量法是用复数表示正弦量的方法，将时域分析转化为复数域分析，大大简化了交流电路的计算。',
         'difficulty': 2, 'learning_hours': 3,
         'formulas': ['U = U_m∠φ', 'u(t) = U_m×cos(ωt+φ)']},
        {'id': 15, 'label': '三相电路', 'group': 'circuit', 'title': 'Y/Δ连接', 'level': 2,
         'description': '三相电路是电力系统的基础，包括星形(Y)和三角形(Δ)两种连接方式。三相系统具有功率传输效率高、电压稳定等优点。',
         'difficulty': 3, 'learning_hours': 4,
         'formulas': ['U_L = √3×U_P', 'I_L = I_P (Y连接)', 'I_L = √3×I_P (Δ连接)']},
        {'id': 16, 'label': '对称分量法', 'group': 'circuit', 'title': '三相不平衡分析', 'level': 3,
         'description': '对称分量法是将不平衡三相系统分解为正序、负序、零序三个对称分量的方法，用于分析三相不平衡故障。',
         'difficulty': 4, 'learning_hours': 4,
         'formulas': ['I_1 = (I_a + a×I_b + a²×I_c)/3', 'I_2 = (I_a + a²×I_b + a×I_c)/3', 'I_0 = (I_a + I_b + I_c)/3']},
        {'id': 17, 'label': '谐波分析', 'group': 'circuit', 'title': '傅里叶级数', 'level': 3,
         'description': '谐波分析使用傅里叶级数将周期信号分解为基波和各次谐波的叠加，是分析非线性电路和电力系统谐波的基础。',
         'difficulty': 4, 'learning_hours': 5,
         'formulas': ['f(t) = a₀/2 + Σ(a_n×cos(nωt) + b_n×sin(nωt))', 'a_n = (2/T)×∫f(t)×cos(nωt)dt']},
        
        # 动态电路
        {'id': 20, 'label': '一阶电路', 'group': 'circuit', 'title': 'RC/RL电路响应', 'level': 2,
         'description': '一阶电路包含一个储能元件(电容或电感)，其响应可以用一阶微分方程描述。包括RC电路和RL电路两种基本类型。',
         'difficulty': 2, 'learning_hours': 3,
         'formulas': ['τ = RC (RC电路)', 'τ = L/R (RL电路)', 'u(t) = u(∞) + [u(0) - u(∞)]×e^(-t/τ)']},
        {'id': 21, 'label': '二阶电路', 'group': 'circuit', 'title': 'RLC电路分析', 'level': 2,
         'description': '二阶电路包含两个储能元件，其响应可以用二阶微分方程描述。根据阻尼系数不同，分为过阻尼、欠阻尼和临界阻尼三种情况。',
         'difficulty': 3, 'learning_hours': 4,
         'formulas': ['α = R/(2L)', 'ω₀ = 1/√(LC)', 'ζ = α/ω₀ (阻尼系数)']},
        {'id': 22, 'label': '阶跃响应', 'group': 'circuit', 'title': '单位阶跃函数', 'level': 2,
         'description': '阶跃响应是电路在单位阶跃信号激励下的响应，是分析电路动态特性的重要方法。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['u(t) = 1 (t≥0)', 'u(t) = 0 (t<0)']},
        {'id': 23, 'label': '冲激响应', 'group': 'circuit', 'title': 'δ函数响应', 'level': 3,
         'description': '冲激响应是电路在单位冲激信号激励下的响应，是系统特性的重要表征。通过冲激响应可以分析任意输入信号的响应。',
         'difficulty': 4, 'learning_hours': 3,
         'formulas': ['δ(t) = ∞ (t=0)', 'δ(t) = 0 (t≠0)', '∫δ(t)dt = 1']},
        {'id': 24, 'label': '卷积积分', 'group': 'circuit', 'title': '时域分析', 'level': 3,
         'description': '卷积积分用于计算线性时不变系统对任意输入信号的响应，是时域分析的重要工具。',
         'difficulty': 4, 'learning_hours': 4,
         'formulas': ['y(t) = ∫h(τ)×x(t-τ)dτ', 'y(t) = h(t) * x(t)']},
        
        # 磁路和变压器
        {'id': 30, 'label': '磁路', 'group': 'circuit', 'title': '磁通量分析', 'level': 2,
         'description': '磁路是磁通量流通的路径，类似于电路中的电流路径。磁路分析是变压器、电机等设备设计的基础。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['Φ = NI/R_m', 'R_m = l/(μA)', 'F = NI (磁动势)']},
        {'id': 31, 'label': '互感', 'group': 'circuit', 'title': '耦合电感', 'level': 2,
         'description': '互感是描述两个线圈之间磁耦合程度的参数，当一个线圈的电流变化时，会在另一个线圈中产生感应电动势。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['M = k×√(L₁×L₂)', 'u₂ = M×di₁/dt', 'k = M/√(L₁×L₂) (耦合系数)']},
        {'id': 32, 'label': '理想变压器', 'group': 'circuit', 'title': '电压电流变换', 'level': 2,
         'description': '理想变压器是理想化的变压器模型，具有无损耗、无漏磁、磁导率无限大等特点。用于电压和电流的变换。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['U₁/U₂ = N₁/N₂ = n', 'I₁/I₂ = N₂/N₁ = 1/n', 'Z₁ = n²×Z₂']},
        {'id': 33, 'label': '实际变压器', 'group': 'circuit', 'title': '损耗和漏感', 'level': 3,
         'description': '实际变压器考虑铜损、铁损、漏磁等实际因素，是理想变压器的扩展模型，更接近实际工作情况。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['P_loss = P_cu + P_fe', 'L_σ = L - M²/L']},
        {'id': 34, 'label': '自耦变压器', 'group': 'circuit', 'title': '单绕组变压器', 'level': 3,
         'description': '自耦变压器只有一个绕组，通过抽头实现电压变换。相比普通变压器，具有体积小、效率高的优点。',
         'difficulty': 3, 'learning_hours': 2,
         'formulas': ['U₁/U₂ = N₁/N₂', 'I₁/I₂ = N₂/N₁']},
        
        # 频域分析
        {'id': 40, 'label': '拉普拉斯变换', 'group': 'circuit', 'title': 's域分析', 'level': 3,
         'description': '拉普拉斯变换将时域函数转换为复频域(s域)函数，将微分方程转化为代数方程，是分析线性时不变系统的重要工具。',
         'difficulty': 4, 'learning_hours': 5,
         'formulas': ['F(s) = ∫f(t)×e^(-st)dt', 'L{df/dt} = s×F(s) - f(0)', 'L{∫f(t)dt} = F(s)/s']},
        {'id': 41, 'label': '网络函数', 'group': 'circuit', 'title': '传递函数H(s)', 'level': 3,
         'description': '网络函数是电路在复频域中的响应与激励的比值，描述了电路的传输特性。包括阻抗函数、导纳函数、传输函数等。',
         'difficulty': 4, 'learning_hours': 4,
         'formulas': ['H(s) = Y(s)/X(s)', 'H(s) = N(s)/D(s)', 'H(jω) = |H(jω)|∠φ(ω)']},
        {'id': 42, 'label': '频率响应', 'group': 'circuit', 'title': '波特图', 'level': 3,
         'description': '频率响应描述电路对不同频率信号的响应特性，通常用波特图表示幅频特性和相频特性。',
         'difficulty': 3, 'learning_hours': 4,
         'formulas': ['|H(jω)| (幅频特性)', 'φ(ω) (相频特性)', '20log|H(jω)| (dB)']},
        {'id': 43, 'label': '极点零点', 'group': 'circuit', 'title': '系统稳定性', 'level': 3,
         'description': '极点和零点是网络函数的重要特征，极点的位置决定了系统的稳定性和动态响应特性。',
         'difficulty': 4, 'learning_hours': 4,
         'formulas': ['H(s) = K×(s-z₁)(s-z₂).../(s-p₁)(s-p₂)...', 'Re(p_i) < 0 (稳定条件)']},
        {'id': 44, 'label': '滤波器特性', 'group': 'circuit', 'title': '通带阻带', 'level': 3,
         'description': '滤波器特性包括通带、阻带、过渡带等概念，描述了滤波器对不同频率信号的传输特性。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['ω_c (截止频率)', 'BW = ω_H - ω_L (带宽)', 'Q = ω₀/BW (品质因数)']},
        
        # 二端口网络
        {'id': 50, 'label': '二端口网络', 'group': 'circuit', 'title': 'Z/Y/H/G参数', 'level': 3,
         'description': '二端口网络是具有两个端口的网络，可以用不同的参数矩阵描述其特性，包括Z参数、Y参数、H参数、G参数等。',
         'difficulty': 3, 'learning_hours': 4,
         'formulas': ['[U₁; U₂] = [Z]×[I₁; I₂]', '[I₁; I₂] = [Y]×[U₁; U₂]', '[U₁; I₂] = [H]×[I₁; U₂]']},
        {'id': 51, 'label': '传输参数', 'group': 'circuit', 'title': 'ABCD参数', 'level': 3,
         'description': '传输参数(ABCD参数)用于描述二端口网络的传输特性，特别适用于级联网络的连接。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['[U₁; I₁] = [A B; C D]×[U₂; -I₂]', 'A = U₁/U₂|I₂=0', 'B = U₁/(-I₂)|U₂=0']},
        {'id': 52, 'label': '网络互联', 'group': 'circuit', 'title': '级联并联', 'level': 3,
         'description': '网络互联包括级联、并联、串联等方式，不同连接方式下参数矩阵的计算方法不同。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['[T] = [T₁]×[T₂] (级联)', '[Y] = [Y₁] + [Y₂] (并联)', '[Z] = [Z₁] + [Z₂] (串联)']},
        
        # ============ 模拟电子技术 (ID: 100-199) ============
        {'id': 100, 'label': '模拟电子技术', 'group': 'analog', 'title': '模电基础', 'level': 0,
         'description': '模拟电子技术研究连续信号的放大、滤波、振荡等处理，是电子工程的重要基础课程。包括半导体器件、放大电路、反馈电路等内容。',
         'difficulty': 1, 'learning_hours': 0},
        
        # 半导体器件
        {'id': 101, 'label': '二极管', 'group': 'analog', 'title': 'PN结特性', 'level': 1,
         'description': '二极管是由PN结构成的半导体器件，具有单向导电性。正向导通，反向截止，是电子电路中最基本的非线性元件。',
         'difficulty': 1, 'learning_hours': 3,
         'formulas': ['I = I_S×(e^(U/UT) - 1)', 'U_T = kT/q ≈ 26mV (室温)']},
        {'id': 102, 'label': '三极管', 'group': 'analog', 'title': 'BJT工作原理', 'level': 1,
         'description': '双极型晶体管(BJT)是一种电流控制型器件，通过基极电流控制集电极电流。包括NPN和PNP两种类型，是放大电路的核心器件。',
         'difficulty': 2, 'learning_hours': 4,
         'formulas': ['I_C = β×I_B', 'I_E = I_B + I_C', 'β = I_C/I_B (电流放大系数)']},
        {'id': 103, 'label': '场效应管', 'group': 'analog', 'title': 'MOSFET/JFET', 'level': 1,
         'description': '场效应管(FET)是一种电压控制型器件，通过栅极电压控制漏极电流。包括MOSFET和JFET两种类型，具有输入阻抗高、功耗低等优点。',
         'difficulty': 2, 'learning_hours': 4,
         'formulas': ['I_D = K×(U_GS - U_th)² (饱和区)', 'g_m = ∂I_D/∂U_GS (跨导)']},
        {'id': 104, 'label': '稳压二极管', 'group': 'analog', 'title': '齐纳二极管', 'level': 2,
         'description': '稳压二极管利用反向击穿特性实现电压稳定，当反向电压达到击穿电压时，电压基本保持不变。常用于稳压电路。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['U_Z (稳压值)', 'I_Zmin < I_Z < I_Zmax']},
        {'id': 105, 'label': '发光二极管', 'group': 'analog', 'title': 'LED特性', 'level': 2,
         'description': '发光二极管(LED)是一种能将电能转化为光能的半导体器件，具有效率高、寿命长、响应快等优点，广泛应用于照明和显示。',
         'difficulty': 1, 'learning_hours': 1},
        {'id': 106, 'label': '光电二极管', 'group': 'analog', 'title': '光敏特性', 'level': 2,
         'description': '光电二极管是一种能将光能转化为电能的半导体器件，在光照下产生光电流，常用于光检测和光通信。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['I_ph = η×P_opt (光电流)', 'η (量子效率)']},
        
        # 运算放大器
        {'id': 110, 'label': '运算放大器', 'group': 'analog', 'title': '理想运放特性', 'level': 1,
         'description': '运算放大器是一种高增益、直接耦合的差分放大器。理想运放具有无限大增益、无限大输入阻抗、零输出阻抗等特点。',
         'difficulty': 2, 'learning_hours': 3,
         'formulas': ['A_v = ∞', 'R_in = ∞', 'R_out = 0', 'V_out = A_v × (V+ - V-)'],
         'keywords': ['差分放大', '高增益', '负反馈', '虚短虚断'],
         'prerequisites': [102, 120],
         'examples': ['同相放大器设计', '反相放大器设计', '电压跟随器']},
        {'id': 111, 'label': '同相放大器', 'group': 'analog', 'title': '电压跟随器', 'level': 2,
         'description': '同相放大器的输入信号加在同相输入端，输出与输入同相。当反馈电阻为零时成为电压跟随器，具有高输入阻抗、低输出阻抗的特点。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['A_v = 1 + R_f/R_1', 'U_out = (1 + R_f/R_1)×U_in']},
        {'id': 112, 'label': '反相放大器', 'group': 'analog', 'title': '负反馈放大', 'level': 2,
         'description': '反相放大器的输入信号加在反相输入端，输出与输入反相。是最基本的运放应用电路，增益由反馈电阻决定。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['A_v = -R_f/R_1', 'U_out = -(R_f/R_1)×U_in']},
        {'id': 113, 'label': '差分放大器', 'group': 'analog', 'title': '差模共模', 'level': 2,
         'description': '差分放大器放大两个输入信号的差值，抑制共模信号。具有高共模抑制比(CMRR)，常用于信号处理和测量电路。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['A_d = R_f/R_1 (差模增益)', 'CMRR = A_d/A_c (共模抑制比)']},
        {'id': 114, 'label': '积分电路', 'group': 'analog', 'title': 'RC积分器', 'level': 2,
         'description': '积分电路输出信号是输入信号的积分，由运放和电容构成。常用于波形变换、信号处理等应用。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['U_out = -(1/RC)×∫U_in dt', 'τ = RC (时间常数)']},
        {'id': 115, 'label': '微分电路', 'group': 'analog', 'title': 'RC微分器', 'level': 2,
         'description': '微分电路输出信号是输入信号的微分，由运放和电容构成。常用于信号检测和波形变换。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['U_out = -RC×dU_in/dt']},
        {'id': 116, 'label': '比较器', 'group': 'analog', 'title': '电压比较', 'level': 2,
         'description': '比较器比较两个输入电压的大小，输出高电平或低电平。是数字电路和模拟电路的接口，常用于信号检测和阈值判断。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['U_out = V_CC (U+ > U-)', 'U_out = V_EE (U+ < U-)']},
        {'id': 117, 'label': '施密特触发器', 'group': 'analog', 'title': '滞回比较器', 'level': 2,
         'description': '施密特触发器是具有滞回特性的比较器，具有两个阈值电压，可以消除噪声干扰，常用于波形整形。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['U_H = (R_1/(R_1+R_2))×V_CC', 'U_L = -(R_1/(R_1+R_2))×V_EE']},
        
        # 放大电路
        {'id': 120, 'label': '放大电路', 'group': 'analog', 'title': '基本放大结构', 'level': 2,
         'description': '放大电路是模拟电路的核心，用于放大信号的幅度。根据输入输出端的不同，分为共射、共基、共集三种基本组态。',
         'difficulty': 2, 'learning_hours': 4},
        {'id': 121, 'label': '共射放大', 'group': 'analog', 'title': 'CE放大电路', 'level': 2,
         'description': '共射放大电路具有电压和电流放大能力，是最常用的放大电路组态。输入阻抗中等，输出阻抗较高。',
         'difficulty': 2, 'learning_hours': 3,
         'formulas': ['A_v = -β×R_C/r_be', 'r_be = r_bb\' + (1+β)×U_T/I_E']},
        {'id': 122, 'label': '共基放大', 'group': 'analog', 'title': 'CB放大电路', 'level': 2,
         'description': '共基放大电路具有电压放大能力，但电流放大系数小于1。输入阻抗低，输出阻抗高，频率特性好。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['A_v = α×R_C/r_e', 'α = β/(1+β)', 'r_e = U_T/I_E']},
        {'id': 123, 'label': '共集放大', 'group': 'analog', 'title': 'CC放大电路', 'level': 2,
         'description': '共集放大电路(射极跟随器)具有电流放大能力，电压放大系数接近1。输入阻抗高，输出阻抗低，常用作阻抗变换。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['A_v ≈ 1', 'R_in = r_be + (1+β)×R_E', 'R_out ≈ R_E//(r_be/(1+β))']},
        {'id': 124, 'label': '多级放大', 'group': 'analog', 'title': '级联放大', 'level': 2,
         'description': '多级放大电路通过级联多个单级放大器实现更大的增益。需要考虑级间耦合方式和频率响应。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['A_v = A_v1×A_v2×...×A_vn', 'BW_total < BW_single']},
        {'id': 125, 'label': '功率放大', 'group': 'analog', 'title': 'A/B/AB类功放', 'level': 2,
         'description': '功率放大器用于驱动负载，要求输出功率大、效率高。根据工作点不同分为A类、B类、AB类等。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['η = P_out/P_dc (效率)', 'η_A = 25%', 'η_B = 78.5%', 'η_AB = 50-70%']},
        {'id': 126, 'label': '小信号模型', 'group': 'analog', 'title': 'h参数模型', 'level': 3,
         'description': '小信号模型用于分析放大电路的小信号特性，包括h参数模型、混合π模型等。将非线性器件线性化处理。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['h_ie = r_be', 'h_fe = β', 'h_oe = 1/r_ce']},
        {'id': 127, 'label': '频率响应', 'group': 'analog', 'title': '带宽分析', 'level': 3,
         'description': '频率响应描述放大器对不同频率信号的放大能力，包括上限频率、下限频率和带宽等参数。',
         'difficulty': 3, 'learning_hours': 4,
         'formulas': ['f_H (上限频率)', 'f_L (下限频率)', 'BW = f_H - f_L (带宽)', 'GBW = A_v×BW (增益带宽积)']},
        
        # 反馈电路
        {'id': 130, 'label': '反馈电路', 'group': 'analog', 'title': '反馈原理', 'level': 2,
         'description': '反馈电路将输出信号的一部分送回输入端，根据反馈极性分为正反馈和负反馈。负反馈可以改善电路性能，正反馈用于振荡器。',
         'difficulty': 3, 'learning_hours': 4},
        {'id': 131, 'label': '负反馈', 'group': 'analog', 'title': '稳定性改善', 'level': 2,
         'description': '负反馈可以稳定增益、扩展带宽、减小失真、改变输入输出阻抗等，是改善放大器性能的重要手段。',
         'difficulty': 3, 'learning_hours': 4,
         'formulas': ['A_f = A/(1+AF)', 'F = X_f/X_o (反馈系数)', '1+AF (反馈深度)']},
        {'id': 132, 'label': '正反馈', 'group': 'analog', 'title': '振荡条件', 'level': 2,
         'description': '正反馈用于产生振荡，满足振幅条件和相位条件时电路可以自激振荡，产生周期信号。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['|AF| ≥ 1 (振幅条件)', 'φ_A + φ_F = 2nπ (相位条件)']},
        {'id': 133, 'label': '反馈类型', 'group': 'analog', 'title': '电压电流反馈', 'level': 3,
         'description': '反馈类型包括电压反馈、电流反馈、串联反馈、并联反馈等，不同类型的反馈对电路性能的影响不同。',
         'difficulty': 3, 'learning_hours': 3},
        
        # 滤波器
        {'id': 140, 'label': '滤波器', 'group': 'analog', 'title': '有源滤波器', 'level': 2,
         'description': '有源滤波器使用运放和RC网络实现滤波功能，相比无源滤波器具有增益可调、体积小等优点。',
         'difficulty': 3, 'learning_hours': 4},
        {'id': 141, 'label': '低通滤波', 'group': 'analog', 'title': 'LPF', 'level': 2,
         'description': '低通滤波器允许低频信号通过，抑制高频信号。常用于去除高频噪声和抗混叠。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['H(s) = 1/(1+sRC)', 'f_c = 1/(2πRC)', 'A_v = -R_f/R_1 (有源)']},
        {'id': 142, 'label': '高通滤波', 'group': 'analog', 'title': 'HPF', 'level': 2,
         'description': '高通滤波器允许高频信号通过，抑制低频信号。常用于去除直流分量和低频干扰。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['H(s) = sRC/(1+sRC)', 'f_c = 1/(2πRC)']},
        {'id': 143, 'label': '带通滤波', 'group': 'analog', 'title': 'BPF', 'level': 2,
         'description': '带通滤波器允许特定频带内的信号通过，抑制其他频率的信号。常用于信号选择和频率分离。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['f_0 = 1/(2π√(R₁R₂C₁C₂))', 'Q = f_0/BW', 'BW = f_H - f_L']},
        {'id': 144, 'label': '带阻滤波', 'group': 'analog', 'title': 'BSF', 'level': 2,
         'description': '带阻滤波器抑制特定频带内的信号，允许其他频率的信号通过。常用于去除特定频率的干扰。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['f_0 = 1/(2π√(LC))', 'Q = f_0/BW']},
        {'id': 145, 'label': '巴特沃斯', 'group': 'analog', 'title': 'Butterworth响应', 'level': 3,
         'description': '巴特沃斯滤波器具有最平坦的通带响应，在通带内没有纹波，但过渡带较宽。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['|H(jω)|² = 1/(1+(ω/ω_c)^(2n))', 'n (滤波器阶数)']},
        {'id': 146, 'label': '切比雪夫', 'group': 'analog', 'title': 'Chebyshev响应', 'level': 3,
         'description': '切比雪夫滤波器在通带内具有等纹波特性，过渡带比巴特沃斯更陡，但通带内有纹波。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['|H(jω)|² = 1/(1+ε²×C_n²(ω/ω_c))', 'C_n (切比雪夫多项式)']},
        
        # 振荡器
        {'id': 150, 'label': '振荡器', 'group': 'analog', 'title': '信号产生', 'level': 2,
         'description': '振荡器利用正反馈产生周期信号，是信号源和时钟电路的核心。根据选频网络不同分为LC、RC、晶体振荡器等。',
         'difficulty': 3, 'learning_hours': 4},
        {'id': 151, 'label': 'LC振荡', 'group': 'analog', 'title': '谐振振荡', 'level': 2,
         'description': 'LC振荡器利用LC谐振回路作为选频网络，振荡频率由LC参数决定。适用于高频振荡。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['f_0 = 1/(2π√(LC))', 'Q = (1/R)×√(L/C)']},
        {'id': 152, 'label': 'RC振荡', 'group': 'analog', 'title': '相移振荡', 'level': 2,
         'description': 'RC振荡器利用RC网络实现相移和选频，适用于低频振荡。包括相移振荡器和文氏桥振荡器等。',
         'difficulty': 2, 'learning_hours': 3,
         'formulas': ['f_0 = 1/(2πRC√6) (相移)', 'f_0 = 1/(2πRC) (文氏桥)']},
        {'id': 153, 'label': '晶体振荡', 'group': 'analog', 'title': '晶振电路', 'level': 2,
         'description': '晶体振荡器利用石英晶体的压电效应实现高精度、高稳定度的振荡，广泛应用于时钟电路和频率标准。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['f_0 = 1/(2π√(L_q×C_q))', 'Q ≈ 10⁴-10⁶']},
        {'id': 154, 'label': '文氏桥振荡', 'group': 'analog', 'title': 'Wien桥', 'level': 3,
         'description': '文氏桥振荡器是一种RC振荡器，利用文氏桥网络实现选频和正反馈，具有频率可调、波形好等优点。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['f_0 = 1/(2πRC)', 'A_v ≥ 3 (起振条件)']},
        
        # 电源电路
        {'id': 160, 'label': '稳压电路', 'group': 'analog', 'title': '电压稳定', 'level': 2,
         'description': '稳压电路用于提供稳定的直流电压，包括线性稳压和开关稳压两种类型。是电子系统的重要组成部分。',
         'difficulty': 2, 'learning_hours': 3},
        {'id': 161, 'label': '线性稳压', 'group': 'analog', 'title': 'LDO', 'level': 2,
         'description': '线性稳压器(LDO)通过调整管工作在线性区实现稳压，具有纹波小、噪声低的优点，但效率较低。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['U_out = U_ref×(1+R_2/R_1)', 'η = U_out/U_in', 'P_loss = (U_in-U_out)×I_out']},
        {'id': 162, 'label': '开关稳压', 'group': 'analog', 'title': 'DC-DC变换', 'level': 2,
         'description': '开关稳压器通过开关管工作在开关状态实现稳压，具有效率高、体积小的优点，但纹波较大。',
         'difficulty': 3, 'learning_hours': 4,
         'formulas': ['U_out = D×U_in (Buck)', 'U_out = U_in/(1-D) (Boost)', 'η = P_out/P_in', 'D (占空比)']},
        {'id': 163, 'label': '整流电路', 'group': 'analog', 'title': 'AC-DC', 'level': 2,
         'description': '整流电路将交流电转换为直流电，包括半波整流、全波整流、桥式整流等。是电源电路的第一级。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['U_dc = 0.45×U_ac (半波)', 'U_dc = 0.9×U_ac (全波)', 'U_dc = 0.9×U_ac (桥式)']},
        {'id': 164, 'label': '滤波电路', 'group': 'analog', 'title': '平滑滤波', 'level': 2,
         'description': '滤波电路用于平滑整流后的脉动直流，通常使用电容滤波或LC滤波，减小输出电压的纹波。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['U_ripple = I_load/(f×C)', 'τ = RC', 'C ≥ I_load/(f×U_ripple)']},
        
        # ============ 数字电子技术 (ID: 200-299) ============
        {'id': 200, 'label': '数字电子技术', 'group': 'digital', 'title': '数电基础', 'level': 0,
         'description': '数字电子技术研究离散信号的逻辑运算、存储和处理，是现代电子系统的基础。包括逻辑门、组合逻辑、时序逻辑、存储器等内容。',
         'difficulty': 1, 'learning_hours': 0},
        
        # 逻辑基础
        {'id': 201, 'label': '逻辑门', 'group': 'digital', 'title': '与或非门', 'level': 1,
         'description': '逻辑门是数字电路的基本构建单元，实现基本的逻辑运算。包括与门(AND)、或门(OR)、非门(NOT)、与非门(NAND)、或非门(NOR)、异或门(XOR)等。',
         'difficulty': 1, 'learning_hours': 2,
         'formulas': ['Y = A·B (与门)', 'Y = A+B (或门)', 'Y = A\' (非门)', 'Y = A⊕B (异或门)'],
         'keywords': ['布尔运算', '真值表', '逻辑功能', '数字电路基础'],
         'prerequisites': [],
         'examples': ['与门实现逻辑与', '或门实现逻辑或', '非门实现逻辑非']},
        {'id': 202, 'label': '布尔代数', 'group': 'digital', 'title': '逻辑运算', 'level': 1,
         'description': '布尔代数是数字逻辑的数学基础，定义了逻辑运算的规则和定律，用于逻辑函数的分析和化简。',
         'difficulty': 1, 'learning_hours': 3,
         'formulas': ['A·A = A', 'A+A = A', 'A·(B+C) = A·B + A·C', 'A+B·C = (A+B)·(A+C)', 'A+A\' = 1', 'A·A\' = 0']},
        {'id': 203, 'label': '卡诺图', 'group': 'digital', 'title': '逻辑化简', 'level': 2,
         'description': '卡诺图是逻辑函数化简的图形方法，通过相邻最小项的合并实现逻辑函数的简化，适用于4变量以下的函数。',
         'difficulty': 2, 'learning_hours': 3},
        {'id': 204, 'label': '逻辑函数', 'group': 'digital', 'title': '最小项最大项', 'level': 2,
         'description': '逻辑函数可以用最小项之和或最大项之积的形式表示，是逻辑函数标准形式，便于分析和实现。',
         'difficulty': 2, 'learning_hours': 3,
         'formulas': ['F = Σm_i (最小项)', 'F = ΠM_i (最大项)', 'm_i = ∏x_j (x_j=1或x_j\')']},
        
        # 组合逻辑
        {'id': 210, 'label': '组合逻辑', 'group': 'digital', 'title': '无记忆逻辑', 'level': 2,
         'description': '组合逻辑电路的输出只取决于当前输入，没有记忆功能。包括编码器、译码器、多路选择器等基本组合逻辑电路。',
         'difficulty': 2, 'learning_hours': 4},
        {'id': 211, 'label': '编码器', 'group': 'digital', 'title': '编码电路', 'level': 2,
         'description': '编码器将多个输入信号编码为二进制输出，包括普通编码器和优先编码器。常用于键盘输入和地址编码。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['Y = f(I_0, I_1, ..., I_n)', 'n位输出可编码2^n个输入']},
        {'id': 212, 'label': '译码器', 'group': 'digital', 'title': '解码电路', 'level': 2,
         'description': '译码器将二进制输入译码为多个输出，包括2-4译码器、3-8译码器等。常用于地址译码和显示驱动。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['Y_i = 1 (当输入=i)', 'n位输入可译码为2^n个输出']},
        {'id': 213, 'label': '多路选择器', 'group': 'digital', 'title': 'MUX', 'level': 2,
         'description': '多路选择器(MUX)从多个输入中选择一个输出，选择由地址信号控制。常用于数据选择和路由。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['Y = D_i (当S=i)', 'n位地址可选择2^n个输入']},
        {'id': 214, 'label': '多路分配器', 'group': 'digital', 'title': 'DEMUX', 'level': 2,
         'description': '多路分配器(DEMUX)将一个输入分配到多个输出之一，是MUX的逆操作。常用于数据分配。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['Y_i = D (当S=i)', 'Y_j = 0 (当j≠i)']},
        {'id': 215, 'label': '加法器', 'group': 'digital', 'title': '全加器', 'level': 2,
         'description': '加法器实现二进制数的加法运算，包括半加器和全加器。全加器考虑进位输入，是算术运算的基础。',
         'difficulty': 2, 'learning_hours': 3,
         'formulas': ['S = A⊕B⊕C_in', 'C_out = A·B + (A⊕B)·C_in', 'S = A+B+C_in (和)', 'C_out (进位)']},
        {'id': 216, 'label': '比较器', 'group': 'digital', 'title': '数值比较', 'level': 2,
         'description': '比较器比较两个二进制数的大小，输出大于、等于、小于三种结果。是数值运算和排序的基础。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['A>B, A=B, A<B (输出)', '从高位到低位逐位比较']},
        {'id': 217, 'label': 'ALU', 'group': 'digital', 'title': '算术逻辑单元', 'level': 3,
         'description': '算术逻辑单元(ALU)是CPU的核心部件，实现算术运算(加减)和逻辑运算(与或非)。是计算机运算的基础。',
         'difficulty': 3, 'learning_hours': 4,
         'formulas': ['F = f(A, B, S)', 'S (功能选择)', 'C_out (进位输出)']},
        
        # 时序逻辑
        {'id': 220, 'label': '时序逻辑', 'group': 'digital', 'title': '有记忆逻辑', 'level': 2,
         'description': '时序逻辑电路的输出不仅取决于当前输入，还取决于历史状态，具有记忆功能。包括触发器、计数器、寄存器等。',
         'difficulty': 2, 'learning_hours': 4},
        {'id': 221, 'label': '触发器', 'group': 'digital', 'title': 'SR/JK/D/T', 'level': 2,
         'description': '触发器是时序电路的基本存储单元，包括SR触发器、JK触发器、D触发器、T触发器。用于存储1位二进制信息。',
         'difficulty': 2, 'learning_hours': 4,
         'formulas': ['Q(n+1) = S + R\'·Q(n) (SR)', 'Q(n+1) = J·Q\'(n) + K\'·Q(n) (JK)', 'Q(n+1) = D (D触发器)']},
        {'id': 222, 'label': '锁存器', 'group': 'digital', 'title': 'Latch', 'level': 2,
         'description': '锁存器是电平触发的存储单元，在使能信号有效时输出跟随输入，常用于数据暂存。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['Q = D (当EN=1)', 'Q保持 (当EN=0)']},
        {'id': 223, 'label': '计数器', 'group': 'digital', 'title': '同步/异步', 'level': 3,
         'description': '计数器实现计数功能，包括同步计数器和异步计数器。同步计数器所有触发器同时翻转，速度更快。',
         'difficulty': 3, 'learning_hours': 4,
         'formulas': ['Q(n+1) = Q(n) + 1', '模M计数器: 0到M-1循环', 'f_out = f_clk/M']},
        {'id': 224, 'label': '寄存器', 'group': 'digital', 'title': '数据存储', 'level': 2,
         'description': '寄存器用于存储多位二进制数据，由多个触发器组成。是CPU和数字系统的重要存储单元。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['Q = D (当CLK上升沿)', 'n位寄存器存储n位数据']},
        {'id': 225, 'label': '移位寄存器', 'group': 'digital', 'title': '串并转换', 'level': 3,
         'description': '移位寄存器实现数据的移位功能，可以左移、右移，常用于串并转换、数据缓冲等应用。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['Q_i(n+1) = Q_(i-1)(n) (右移)', 'Q_i(n+1) = Q_(i+1)(n) (左移)']},
        {'id': 226, 'label': '状态机', 'group': 'digital', 'title': '有限状态机', 'level': 3,
         'description': '有限状态机(FSM)是时序逻辑的高级应用，用状态和状态转换描述系统行为。包括Moore型和Mealy型两种。',
         'difficulty': 4, 'learning_hours': 5,
         'formulas': ['S(n+1) = f(S(n), X(n))', 'Y(n) = g(S(n)) (Moore)', 'Y(n) = g(S(n), X(n)) (Mealy)']},
        
        # 存储器
        {'id': 230, 'label': '存储器', 'group': 'digital', 'title': '数据存储', 'level': 2,
         'description': '存储器用于存储数据和程序，包括RAM、ROM、Flash等类型。是计算机系统的重要组成部分。',
         'difficulty': 2, 'learning_hours': 3},
        {'id': 231, 'label': 'RAM', 'group': 'digital', 'title': '随机存取', 'level': 2,
         'description': '随机存取存储器(RAM)可以随机读写，但断电后数据丢失。包括SRAM和DRAM两种类型，用于临时数据存储。',
         'difficulty': 2, 'learning_hours': 3,
         'formulas': ['容量 = 2^N (N位地址)', '访问时间 (ns)', '带宽 = 数据宽度×频率']},
        {'id': 232, 'label': 'ROM', 'group': 'digital', 'title': '只读存储', 'level': 2,
         'description': '只读存储器(ROM)只能读取不能写入，断电后数据不丢失。用于存储固定程序和常数。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['容量 = 2^N×M (N位地址, M位数据)']},
        {'id': 233, 'label': 'Flash', 'group': 'digital', 'title': '闪存', 'level': 2,
         'description': 'Flash存储器可以电擦除和编程，具有非易失性。包括NOR Flash和NAND Flash，广泛应用于存储设备。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['擦除次数 (10^4-10^6次)', '编程时间 (ms)', '读取时间 (ns)']},
        {'id': 234, 'label': '缓存', 'group': 'digital', 'title': 'Cache', 'level': 3,
         'description': '缓存是高速小容量存储器，用于存储CPU频繁访问的数据，提高系统性能。采用命中率和替换算法管理。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['命中率 = 命中次数/总访问次数', '平均访问时间 = 命中率×T_cache + (1-命中率)×T_memory']},
        
        # 数模转换
        {'id': 240, 'label': 'ADC', 'group': 'digital', 'title': '模数转换器', 'level': 2,
         'description': '模数转换器(ADC)将模拟信号转换为数字信号，包括逐次逼近型、积分型、并行比较型等。是数字信号处理的前端。',
         'difficulty': 3, 'learning_hours': 4,
         'formulas': ['分辨率 = 1/2^N', '量化步长 = V_ref/2^N', 'SNR = 6.02×N + 1.76 (dB)']},
        {'id': 241, 'label': 'DAC', 'group': 'digital', 'title': '数模转换器', 'level': 2,
         'description': '数模转换器(DAC)将数字信号转换为模拟信号，包括权电阻型、R-2R网络型、电流型等。是数字信号处理的输出。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['V_out = (D/2^N)×V_ref', 'D (数字输入)', '分辨率 = V_ref/2^N']},
        {'id': 242, 'label': '采样定理', 'group': 'digital', 'title': '奈奎斯特定理', 'level': 2,
         'description': '奈奎斯特采样定理指出，采样频率必须大于信号最高频率的2倍，才能无失真地恢复原始信号。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['f_s ≥ 2×f_max', 'f_s (采样频率)', 'f_max (信号最高频率)']},
        {'id': 243, 'label': '量化误差', 'group': 'digital', 'title': '分辨率', 'level': 3,
         'description': '量化误差是模拟信号数字化过程中的固有误差，由量化步长决定。分辨率越高，量化误差越小。',
         'difficulty': 3, 'learning_hours': 2,
         'formulas': ['量化误差 ≤ ±LSB/2', 'LSB = V_ref/2^N', 'SNR = 20×log(2^N) (dB)']},
        
        # 可编程逻辑
        {'id': 250, 'label': 'FPGA', 'group': 'digital', 'title': '现场可编程', 'level': 3,
         'description': '现场可编程门阵列(FPGA)是一种可编程逻辑器件，通过配置实现任意数字逻辑功能。具有灵活性高、开发周期短等优点。',
         'difficulty': 4, 'learning_hours': 6},
        {'id': 251, 'label': 'CPLD', 'group': 'digital', 'title': '复杂可编程', 'level': 3,
         'description': '复杂可编程逻辑器件(CPLD)是基于乘积项结构的可编程器件，适合实现组合逻辑和简单时序逻辑。',
         'difficulty': 3, 'learning_hours': 4},
        {'id': 252, 'label': 'HDL', 'group': 'digital', 'title': '硬件描述语言', 'level': 3,
         'description': '硬件描述语言(HDL)用于描述数字电路的结构和行为，是FPGA和ASIC设计的主要工具。包括Verilog和VHDL。',
         'difficulty': 3, 'learning_hours': 5},
        {'id': 253, 'label': 'Verilog', 'group': 'digital', 'title': 'Verilog HDL', 'level': 3,
         'description': 'Verilog是一种硬件描述语言，语法类似C语言，广泛应用于数字电路设计和验证。',
         'difficulty': 3, 'learning_hours': 5},
        {'id': 254, 'label': 'VHDL', 'group': 'digital', 'title': 'VHDL语言', 'level': 3,
         'description': 'VHDL是一种硬件描述语言，语法类似Ada语言，在航空航天和国防领域应用广泛。',
         'difficulty': 3, 'learning_hours': 5},
        
        # 数字信号处理
        {'id': 260, 'label': '数字信号处理', 'group': 'digital', 'title': 'DSP', 'level': 2,
         'description': '数字信号处理(DSP)在数字域对信号进行滤波、变换、分析等处理，是现代信号处理的基础。',
         'difficulty': 3, 'learning_hours': 5},
        {'id': 261, 'label': 'FFT', 'group': 'digital', 'title': '快速傅里叶变换', 'level': 3,
         'description': '快速傅里叶变换(FFT)是DFT的快速算法，计算复杂度从O(N²)降低到O(NlogN)，广泛应用于频谱分析。',
         'difficulty': 4, 'learning_hours': 4,
         'formulas': ['X(k) = Σx(n)×W_N^(nk)', 'W_N = e^(-j2π/N)', '计算量: N×log₂N']},
        {'id': 262, 'label': 'FIR滤波', 'group': 'digital', 'title': '有限冲激响应', 'level': 3,
         'description': '有限冲激响应(FIR)滤波器具有线性相位、稳定等优点，但阶数较高。通过卷积实现滤波。',
         'difficulty': 3, 'learning_hours': 4,
         'formulas': ['y(n) = Σh(k)×x(n-k)', 'H(z) = Σh(n)×z^(-n)', '阶数 = N-1']},
        {'id': 263, 'label': 'IIR滤波', 'group': 'digital', 'title': '无限冲激响应', 'level': 3,
         'description': '无限冲激响应(IIR)滤波器具有阶数低、效率高等优点，但可能不稳定。通过递归实现滤波。',
         'difficulty': 4, 'learning_hours': 4,
         'formulas': ['y(n) = Σa_k×y(n-k) + Σb_k×x(n-k)', 'H(z) = B(z)/A(z)', '稳定性: |poles| < 1']},
        
        # ============ 高频电子线路 (ID: 300-399) ============
        {'id': 300, 'label': '高频电子线路', 'group': 'rf', 'title': '高频电路', 'level': 0,
         'description': '高频电子线路研究高频信号的放大、振荡、调制、解调等处理，是通信系统和射频电路的基础。包括谐振电路、高频放大器、混频器、锁相环等。',
         'difficulty': 1, 'learning_hours': 0},
        
        # 谐振电路
        {'id': 301, 'label': '谐振电路', 'group': 'rf', 'title': 'LC谐振', 'level': 1,
         'description': '谐振电路利用LC回路的谐振特性实现选频，是高频电路的基础。包括串联谐振和并联谐振两种类型。',
         'difficulty': 2, 'learning_hours': 3,
         'formulas': ['f_0 = 1/(2π√(LC))', 'Z = R (串联谐振)', 'Z = L/(RC) (并联谐振)']},
        {'id': 302, 'label': '品质因数', 'group': 'rf', 'title': 'Q值', 'level': 2,
         'description': '品质因数Q值描述谐振电路的选频特性，Q值越高，选频特性越好，但带宽越窄。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['Q = ω₀×L/R = 1/(ω₀×C×R)', 'Q = f_0/BW', 'BW = f_0/Q']},
        {'id': 303, 'label': '带宽', 'group': 'rf', 'title': '3dB带宽', 'level': 2,
         'description': '3dB带宽是功率下降一半(或电压下降√2倍)时的频率范围，是衡量电路频率特性的重要参数。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['BW = f_H - f_L', 'BW = f_0/Q', 'f_H, f_L (上下限频率)']},
        {'id': 304, 'label': '耦合谐振', 'group': 'rf', 'title': '双调谐', 'level': 3,
         'description': '耦合谐振电路通过两个谐振回路的耦合实现更复杂的频率特性，可以改善带宽和选择性。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['k = M/√(L₁×L₂) (耦合系数)', 'k < k_c (欠耦合)', 'k = k_c (临界耦合)', 'k > k_c (过耦合)']},
        
        # 高频放大器
        {'id': 310, 'label': '高频放大器', 'group': 'rf', 'title': '调谐放大', 'level': 1,
         'description': '高频放大器用于放大高频信号，包括小信号放大器和功率放大器。需要考虑频率响应、稳定性、噪声等特性。',
         'difficulty': 3, 'learning_hours': 4},
        {'id': 311, 'label': '小信号放大', 'group': 'rf', 'title': '线性放大', 'level': 2,
         'description': '小信号放大器工作在线性区，要求增益高、噪声低、稳定性好。常用于接收机的前端放大。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['A_v = -g_m×Z_L', 'NF (噪声系数)', '稳定性: K > 1']},
        {'id': 312, 'label': '功率放大', 'group': 'rf', 'title': '高频功放', 'level': 2,
         'description': '高频功率放大器要求输出功率大、效率高，通常工作在大信号状态，需要考虑非线性失真。',
         'difficulty': 3, 'learning_hours': 4,
         'formulas': ['P_out = (1/2)×V_out²/R_L', 'η = P_out/P_dc', 'PAE = (P_out-P_in)/P_dc']},
        {'id': 313, 'label': 'A类功放', 'group': 'rf', 'title': '线性功放', 'level': 2,
         'description': 'A类功放工作点在线性区中心，失真小但效率低(理论最大50%)。适用于小功率和线性度要求高的场合。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['η = P_out/P_dc ≤ 50%', 'I_Q = I_max/2']},
        {'id': 314, 'label': 'C类功放', 'group': 'rf', 'title': '高效率', 'level': 2,
         'description': 'C类功放工作点在截止区，效率高(理论最大78.5%)但失真大。适用于大功率和效率要求高的场合。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['η = P_out/P_dc ≤ 78.5%', '导通角 < 180°', 'I_C = I_max×cos(θ/2)']},
        {'id': 315, 'label': '宽带放大', 'group': 'rf', 'title': '宽频带', 'level': 2,
         'description': '宽带放大器在很宽的频率范围内保持增益，不采用调谐回路。适用于多频段和跳频系统。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['GBW = A_v×BW', '增益平坦度 (dB)']},
        
        # 混频器
        {'id': 320, 'label': '混频器', 'group': 'rf', 'title': '频率变换', 'level': 2,
         'description': '混频器实现频率变换，将输入信号频率与本地振荡器频率混频，产生和频和差频。是超外差接收机的核心。',
         'difficulty': 3, 'learning_hours': 4,
         'formulas': ['f_out = f_RF ± f_LO', 'f_IF = |f_RF - f_LO|', 'f_IF (中频)']},
        {'id': 321, 'label': '下变频', 'group': 'rf', 'title': '混频', 'level': 2,
         'description': '下变频将高频信号转换为中频信号，便于后续处理。是接收机中常用的频率变换方式。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['f_IF = f_RF - f_LO (f_RF > f_LO)', 'f_IF = f_LO - f_RF (f_LO > f_RF)']},
        {'id': 322, 'label': '上变频', 'group': 'rf', 'title': '升频', 'level': 2,
         'description': '上变频将中频或基带信号转换为高频信号，用于发射机。是发射机中常用的频率变换方式。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['f_RF = f_IF + f_LO', 'f_RF = f_BB + f_LO']},
        {'id': 323, 'label': '镜像频率', 'group': 'rf', 'title': '干扰抑制', 'level': 3,
         'description': '镜像频率是混频过程中产生的干扰频率，需要通过镜像抑制滤波器或镜像抑制混频器来抑制。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['f_image = f_LO ± f_IF', '镜像抑制比 (dB)']},
        
        # 调制解调
        {'id': 330, 'label': '调制解调', 'group': 'rf', 'title': 'AM/FM/PM', 'level': 2,
         'description': '调制将基带信号加载到载波上，解调从已调信号中恢复基带信号。是通信系统的基础。',
         'difficulty': 3, 'learning_hours': 5},
        {'id': 331, 'label': 'AM调制', 'group': 'rf', 'title': '幅度调制', 'level': 2,
         'description': '幅度调制(AM)用基带信号控制载波的幅度，实现简单但抗噪声能力差。广泛应用于广播系统。',
         'difficulty': 2, 'learning_hours': 3,
         'formulas': ['s(t) = A_c×[1+m×m(t)]×cos(ω_c×t)', 'm (调制指数)', 'BW = 2×f_m']},
        {'id': 332, 'label': 'FM调制', 'group': 'rf', 'title': '频率调制', 'level': 2,
         'description': '频率调制(FM)用基带信号控制载波的频率，抗噪声能力强但带宽较宽。广泛应用于调频广播。',
         'difficulty': 3, 'learning_hours': 4,
         'formulas': ['s(t) = A_c×cos(ω_c×t + β×∫m(t)dt)', 'β (调制指数)', 'BW ≈ 2×(β+1)×f_m']},
        {'id': 333, 'label': 'PM调制', 'group': 'rf', 'title': '相位调制', 'level': 2,
         'description': '相位调制(PM)用基带信号控制载波的相位，与FM类似但实现方式不同。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['s(t) = A_c×cos(ω_c×t + k_p×m(t))', 'k_p (相位灵敏度)']},
        {'id': 334, 'label': 'QAM', 'group': 'rf', 'title': '正交幅度调制', 'level': 3,
         'description': '正交幅度调制(QAM)同时调制载波的幅度和相位，频谱效率高。广泛应用于数字通信系统。',
         'difficulty': 4, 'learning_hours': 4,
         'formulas': ['s(t) = I(t)×cos(ω_c×t) - Q(t)×sin(ω_c×t)', '星座点数 = 2^N', 'N (每符号比特数)']},
        {'id': 335, 'label': 'ASK', 'group': 'rf', 'title': '幅移键控', 'level': 3,
         'description': '幅移键控(ASK)用数字信号控制载波的幅度，实现简单但抗噪声能力差。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['s(t) = A×d(t)×cos(ω_c×t)', 'd(t) = 0或1']},
        {'id': 336, 'label': 'FSK', 'group': 'rf', 'title': '频移键控', 'level': 3,
         'description': '频移键控(FSK)用数字信号控制载波的频率，抗噪声能力强。广泛应用于数字通信。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['f_1 = f_c + Δf (传号)', 'f_0 = f_c - Δf (空号)', 'Δf (频偏)']},
        {'id': 337, 'label': 'PSK', 'group': 'rf', 'title': '相移键控', 'level': 3,
         'description': '相移键控(PSK)用数字信号控制载波的相位，频谱效率高。包括BPSK、QPSK、8PSK等。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['s(t) = A×cos(ω_c×t + φ_i)', 'φ_i = 2π×i/M', 'M (相位点数)']},
        
        # 锁相环
        {'id': 340, 'label': '锁相环', 'group': 'rf', 'title': 'PLL', 'level': 2,
         'description': '锁相环(PLL)是一种反馈控制系统，使输出信号与参考信号保持相位锁定。广泛应用于频率合成、时钟恢复等。',
         'difficulty': 4, 'learning_hours': 5,
         'formulas': ['f_out = N×f_ref', 'N (分频比)', '锁定范围', '捕获范围']},
        {'id': 341, 'label': '鉴相器', 'group': 'rf', 'title': '相位检测', 'level': 3,
         'description': '鉴相器比较两个信号的相位差，输出与相位差成比例的电压。是PLL的核心部件之一。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['V_out = K_d×Δφ', 'K_d (鉴相灵敏度)', 'Δφ (相位差)']},
        {'id': 342, 'label': '压控振荡器', 'group': 'rf', 'title': 'VCO', 'level': 3,
         'description': '压控振荡器(VCO)的输出频率由控制电压决定，是PLL的核心部件。要求线性度好、调谐范围宽。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['f_out = f_0 + K_vco×V_ctrl', 'K_vco (压控灵敏度)', '调谐范围']},
        {'id': 343, 'label': '分频器', 'group': 'rf', 'title': '频率分频', 'level': 3,
         'description': '分频器将输入频率除以分频比，输出频率为输入频率的1/N。用于频率合成和时钟分频。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['f_out = f_in/N', 'N (分频比)', '占空比 = 50%']},
        
        # 天线
        {'id': 350, 'label': '天线', 'group': 'rf', 'title': '电磁辐射', 'level': 2,
         'description': '天线实现电磁波的辐射和接收，是无线通信系统的关键部件。包括偶极天线、微带天线、阵列天线等。',
         'difficulty': 3, 'learning_hours': 4,
         'formulas': ['G (增益)', 'D (方向性)', 'η = R_r/(R_r+R_loss) (效率)']},
        {'id': 351, 'label': '偶极天线', 'group': 'rf', 'title': 'Dipole', 'level': 3,
         'description': '偶极天线是最基本的天线形式，由两根等长的导体组成。具有全向辐射特性，广泛应用于通信系统。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['L = λ/2 (半波偶极)', 'R_in ≈ 73Ω', 'G ≈ 2.15 dBi']},
        {'id': 352, 'label': '微带天线', 'group': 'rf', 'title': 'Patch', 'level': 3,
         'description': '微带天线结构简单、体积小、易于集成，广泛应用于现代无线通信设备。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['L ≈ λ_g/2', 'λ_g = λ/√ε_r', 'ε_r (介电常数)']},
        {'id': 353, 'label': '方向图', 'group': 'rf', 'title': '辐射特性', 'level': 3,
         'description': '方向图描述天线在不同方向的辐射强度，包括E面和H面方向图。是天线设计的重要参数。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['F(θ,φ) (方向图函数)', 'HPBW (半功率波束宽度)', 'SLL (副瓣电平)']},
        
        # 匹配网络
        {'id': 360, 'label': '阻抗匹配', 'group': 'rf', 'title': 'Smith圆图', 'level': 2,
         'description': '阻抗匹配使负载阻抗与源阻抗共轭匹配，实现最大功率传输。Smith圆图是阻抗匹配设计的常用工具。',
         'difficulty': 3, 'learning_hours': 4,
         'formulas': ['Z_L = Z_S* (共轭匹配)', 'Γ = (Z_L-Z_0)/(Z_L+Z_0)', 'VSWR = (1+|Γ|)/(1-|Γ|)']},
        {'id': 361, 'label': 'L型匹配', 'group': 'rf', 'title': 'L网络', 'level': 3,
         'description': 'L型匹配网络由两个电抗元件组成，结构简单，适用于窄带匹配。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['Q = √(R_H/R_L - 1)', 'R_H, R_L (高阻、低阻)']},
        {'id': 362, 'label': 'Π型匹配', 'group': 'rf', 'title': 'Π网络', 'level': 3,
         'description': 'Π型匹配网络由三个电抗元件组成，具有更好的带宽特性，适用于宽带匹配。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['Q = √(R_H/R_L - 1)', '带宽特性更好']},
        {'id': 363, 'label': 'T型匹配', 'group': 'rf', 'title': 'T网络', 'level': 3,
         'description': 'T型匹配网络由三个电抗元件组成，是Π型网络的对偶形式，适用于特定阻抗变换。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['Q = √(R_H/R_L - 1)', '与Π型对偶']},
        
        # 滤波器
        {'id': 370, 'label': '滤波器设计', 'group': 'rf', 'title': 'RF滤波器', 'level': 2,
         'description': 'RF滤波器用于选择特定频段的信号，抑制其他频率的干扰。设计需要考虑插入损耗、带外抑制等参数。',
         'difficulty': 3, 'learning_hours': 4,
         'formulas': ['IL (插入损耗)', 'RL (回波损耗)', '带外抑制 (dB)']},
        {'id': 371, 'label': '带通滤波', 'group': 'rf', 'title': 'BPF', 'level': 2,
         'description': '带通滤波器允许特定频段内的信号通过，抑制其他频率。常用于信道选择和频率分离。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['f_0 = √(f_H×f_L)', 'BW = f_H - f_L', 'Q = f_0/BW']},
        {'id': 372, 'label': '带阻滤波', 'group': 'rf', 'title': 'BSF', 'level': 2,
         'description': '带阻滤波器抑制特定频段内的信号，允许其他频率通过。常用于去除特定频率的干扰。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['f_0 = √(f_H×f_L)', '阻带宽度']},
        {'id': 373, 'label': '声表滤波器', 'group': 'rf', 'title': 'SAW', 'level': 3,
         'description': '声表面波滤波器(SAW)利用压电效应实现滤波，具有体积小、选择性好、稳定性高等优点。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['f_0 = v/(2×d)', 'v (声速)', 'd (指条间距)']},
        
        # 噪声分析
        {'id': 380, 'label': '噪声分析', 'group': 'rf', 'title': '信噪比', 'level': 2,
         'description': '噪声分析是高频电路设计的重要内容，包括热噪声、相位噪声等。噪声限制了系统的灵敏度和动态范围。',
         'difficulty': 3, 'learning_hours': 4,
         'formulas': ['SNR = P_signal/P_noise', 'NF (噪声系数)', '灵敏度']},
        {'id': 381, 'label': '热噪声', 'group': 'rf', 'title': '白噪声', 'level': 3,
         'description': '热噪声是电阻中电子的热运动产生的噪声，是白噪声，功率谱密度与温度成正比。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['P_n = k×T×B', 'k (玻尔兹曼常数)', 'T (绝对温度)', 'B (带宽)']},
        {'id': 382, 'label': '相位噪声', 'group': 'rf', 'title': '频率稳定度', 'level': 3,
         'description': '相位噪声描述振荡器频率的短期稳定性，是通信系统的重要指标。相位噪声会导致信号质量下降。',
         'difficulty': 4, 'learning_hours': 4,
         'formulas': ['L(f) = S_φ(f)/2', 'S_φ(f) (相位噪声功率谱)', '单位: dBc/Hz']},
        {'id': 383, 'label': '噪声系数', 'group': 'rf', 'title': 'NF', 'level': 3,
         'description': '噪声系数描述电路对信噪比的恶化程度，是衡量电路噪声性能的重要参数。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['NF = (SNR_in)/(SNR_out)', 'NF = 10×log(F)', 'F (噪声因子)']},
        
        # ============ 嵌入式系统 (ID: 400-499) ============
        {'id': 400, 'label': '嵌入式系统', 'group': 'embedded', 'title': '嵌入式基础', 'level': 0,
         'description': '嵌入式系统是专用计算机系统，集成了处理器、存储器、外设等，广泛应用于智能设备、物联网、工业控制等领域。',
         'difficulty': 1, 'learning_hours': 0},
        
        # 微控制器
        {'id': 401, 'label': '微控制器', 'group': 'embedded', 'title': 'MCU架构', 'level': 1,
         'description': '微控制器(MCU)将CPU、存储器、外设集成在单一芯片上，是嵌入式系统的核心。具有体积小、功耗低、成本低等优点。',
         'difficulty': 2, 'learning_hours': 4},
        {'id': 402, 'label': 'ARM架构', 'group': 'embedded', 'title': 'ARM处理器', 'level': 1,
         'description': 'ARM架构是一种精简指令集(RISC)架构，具有低功耗、高性能的特点，广泛应用于移动设备和嵌入式系统。',
         'difficulty': 2, 'learning_hours': 4},
        {'id': 403, 'label': 'Cortex-M', 'group': 'embedded', 'title': 'ARM Cortex-M', 'level': 2,
         'description': 'Cortex-M系列是ARM的微控制器内核，专为低功耗、实时应用设计。包括M0、M3、M4、M7等型号。',
         'difficulty': 2, 'learning_hours': 4},
        {'id': 404, 'label': 'Cortex-A', 'group': 'embedded', 'title': '应用处理器', 'level': 2,
         'description': 'Cortex-A系列是ARM的应用处理器内核，性能强大，支持复杂操作系统。广泛应用于智能手机、平板电脑等。',
         'difficulty': 3, 'learning_hours': 5},
        {'id': 405, 'label': '8051', 'group': 'embedded', 'title': '51单片机', 'level': 2,
         'description': '8051是经典的8位微控制器，结构简单、易于学习，是嵌入式系统入门的首选。',
         'difficulty': 2, 'learning_hours': 4},
        {'id': 406, 'label': 'AVR', 'group': 'embedded', 'title': 'Atmel AVR', 'level': 2,
         'description': 'AVR是Atmel公司的8位微控制器系列，具有高性能、低功耗的特点，广泛应用于Arduino等开发平台。',
         'difficulty': 2, 'learning_hours': 3},
        
        # 外设接口
        {'id': 410, 'label': 'GPIO', 'group': 'embedded', 'title': '通用输入输出', 'level': 2,
         'description': '通用输入输出(GPIO)是微控制器最基本的接口，可以配置为输入或输出模式，用于连接外部设备。',
         'difficulty': 1, 'learning_hours': 2,
         'formulas': ['输入: 读取引脚电平', '输出: 设置引脚电平', '上拉/下拉电阻']},
        {'id': 411, 'label': '中断系统', 'group': 'embedded', 'title': '中断处理', 'level': 2,
         'description': '中断系统允许外部事件打断CPU当前执行，提高系统响应速度。包括外部中断、定时器中断、串口中断等。',
         'difficulty': 2, 'learning_hours': 3,
         'formulas': ['中断优先级', '中断向量表', '中断服务程序(ISR)']},
        {'id': 412, 'label': '定时器', 'group': 'embedded', 'title': 'Timer', 'level': 2,
         'description': '定时器用于产生精确的时间间隔，包括定时、计数、PWM生成等功能。是嵌入式系统的重要外设。',
         'difficulty': 2, 'learning_hours': 3,
         'formulas': ['T = (ARR+1)/f_clk', 'ARR (自动重装载值)', 'f_clk (时钟频率)']},
        {'id': 413, 'label': 'PWM', 'group': 'embedded', 'title': '脉宽调制', 'level': 2,
         'description': '脉宽调制(PWM)通过改变脉冲宽度控制平均电压，广泛应用于电机控制、LED调光、DAC等应用。',
         'difficulty': 2, 'learning_hours': 3,
         'formulas': ['占空比 = T_on/T_period', 'V_avg = V_max×占空比', 'f_PWM = f_clk/(ARR+1)']},
        {'id': 414, 'label': 'ADC', 'group': 'embedded', 'title': '模数转换', 'level': 2,
         'description': '模数转换器(ADC)将模拟信号转换为数字信号，是传感器接口和信号采集的关键部件。',
         'difficulty': 2, 'learning_hours': 3,
         'formulas': ['分辨率 = V_ref/2^N', '采样率 (SPS)', '转换时间']},
        {'id': 415, 'label': 'DAC', 'group': 'embedded', 'title': '数模转换', 'level': 2,
         'description': '数模转换器(DAC)将数字信号转换为模拟信号，用于信号生成和模拟输出。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['V_out = (D/2^N)×V_ref', 'D (数字输入)', '分辨率 = V_ref/2^N']},
        
        # 通信接口
        {'id': 420, 'label': 'UART', 'group': 'embedded', 'title': '串口通信', 'level': 2,
         'description': '通用异步收发器(UART)实现串行通信，是最常用的通信接口。包括起始位、数据位、停止位等格式。',
         'difficulty': 2, 'learning_hours': 3,
         'formulas': ['波特率 = f_clk/(16×UBRR)', 'UBRR (波特率寄存器)', '数据格式: 起始位+数据位+停止位']},
        {'id': 421, 'label': 'SPI', 'group': 'embedded', 'title': '串行外设接口', 'level': 2,
         'description': '串行外设接口(SPI)是全双工同步串行总线，包括SCLK、MOSI、MISO、CS四根线。速度快，但需要较多引脚。',
         'difficulty': 2, 'learning_hours': 3,
         'formulas': ['f_SCLK = f_clk/(2×PRESCALER)', '数据宽度: 8/16位', 'CPOL, CPHA (时钟极性)']},
        {'id': 422, 'label': 'I2C', 'group': 'embedded', 'title': '两线总线', 'level': 2,
         'description': 'I2C是两线制串行总线，包括SDA(数据)和SCL(时钟)。支持多主多从，但速度较慢。',
         'difficulty': 2, 'learning_hours': 3,
         'formulas': ['f_SCL = f_clk/(4×PRESCALER)', '标准模式: 100kHz', '快速模式: 400kHz', '地址: 7/10位']},
        {'id': 423, 'label': 'CAN总线', 'group': 'embedded', 'title': '控制器局域网', 'level': 2,
         'description': 'CAN总线是汽车和工业控制中常用的总线标准，具有高可靠性、多主控制、错误检测等特点。',
         'difficulty': 3, 'learning_hours': 4,
         'formulas': ['波特率 = f_clk/(BRP×TSEG)', 'BRP (波特率预分频)', 'TSEG (时间段)']},
        {'id': 424, 'label': 'USB', 'group': 'embedded', 'title': '通用串行总线', 'level': 2,
         'description': 'USB是通用的串行总线标准，支持热插拔、即插即用。包括USB 2.0、USB 3.0等版本。',
         'difficulty': 3, 'learning_hours': 4,
         'formulas': ['USB 2.0: 480 Mbps', 'USB 3.0: 5 Gbps', '端点(Endpoint)', '描述符(Descriptor)']},
        {'id': 425, 'label': '以太网', 'group': 'embedded', 'title': 'Ethernet', 'level': 3,
         'description': '以太网是局域网的标准，支持TCP/IP协议栈。嵌入式以太网用于网络连接和数据传输。',
         'difficulty': 4, 'learning_hours': 5,
         'formulas': ['10/100/1000 Mbps', 'MAC地址', 'IP地址', 'TCP/UDP协议']},
        {'id': 426, 'label': 'WiFi', 'group': 'embedded', 'title': '无线网络', 'level': 3,
         'description': 'WiFi实现无线网络连接，基于IEEE 802.11标准。广泛应用于物联网和智能设备。',
         'difficulty': 3, 'learning_hours': 4,
         'formulas': ['802.11n: 最高600 Mbps', '802.11ac: 最高6.77 Gbps', '频段: 2.4GHz/5GHz']},
        {'id': 427, 'label': '蓝牙', 'group': 'embedded', 'title': 'Bluetooth', 'level': 3,
         'description': '蓝牙是短距离无线通信标准，包括经典蓝牙和低功耗蓝牙(BLE)。广泛应用于移动设备和物联网。',
         'difficulty': 3, 'learning_hours': 4,
         'formulas': ['经典蓝牙: 1-3 Mbps', 'BLE: 1 Mbps', '传输距离: 10-100m', '频段: 2.4GHz']},
        
        # 存储
        {'id': 430, 'label': 'Flash', 'group': 'embedded', 'title': '闪存存储', 'level': 2,
         'description': 'Flash存储器用于存储程序和数据，包括内部Flash和外部Flash。具有非易失性、可擦写等特点。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['容量: KB/MB/GB', '页大小', '块大小', '擦写次数: 10^4-10^6']},
        {'id': 431, 'label': 'EEPROM', 'group': 'embedded', 'title': '电可擦除', 'level': 2,
         'description': 'EEPROM可以按字节擦写，适合存储配置参数和小量数据。擦写次数多，但容量较小。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['容量: KB级', '擦写次数: 10^5-10^6', '按字节擦写']},
        {'id': 432, 'label': 'SD卡', 'group': 'embedded', 'title': '存储卡', 'level': 2,
         'description': 'SD卡是大容量存储设备，通过SPI或SDIO接口连接。广泛应用于数据记录和文件存储。',
         'difficulty': 2, 'learning_hours': 3,
         'formulas': ['容量: GB/TB级', '速度等级: Class 2/4/6/10', 'SDIO/SPI接口']},
        
        # 系统功能
        {'id': 440, 'label': 'DMA', 'group': 'embedded', 'title': '直接内存访问', 'level': 2,
         'description': '直接内存访问(DMA)允许外设直接访问内存，无需CPU参与，提高数据传输效率，减轻CPU负担。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['传输速度 = 数据宽度×时钟频率', 'DMA通道', '传输模式: 单次/循环']},
        {'id': 441, 'label': '看门狗', 'group': 'embedded', 'title': 'WDT', 'level': 2,
         'description': '看门狗定时器用于监控系统运行，如果系统死机未及时喂狗，会自动复位系统，提高系统可靠性。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['超时时间 = (PRESCALER×RLR)/f_clk', 'RLR (重装载值)', '喂狗周期']},
        {'id': 442, 'label': '低功耗', 'group': 'embedded', 'title': 'Power Management', 'level': 2,
         'description': '低功耗设计是嵌入式系统的重要特性，通过降低工作频率、关闭不用的外设、进入睡眠模式等方式降低功耗。',
         'difficulty': 2, 'learning_hours': 3,
         'formulas': ['P = V×I', '动态功耗', '静态功耗', '功耗优化策略']},
        {'id': 443, 'label': '睡眠模式', 'group': 'embedded', 'title': 'Sleep Mode', 'level': 3,
         'description': '睡眠模式是低功耗工作模式，CPU停止运行，部分外设关闭，功耗大幅降低。通过中断唤醒。',
         'difficulty': 2, 'learning_hours': 2,
         'formulas': ['功耗降低: 10-1000倍', '唤醒时间', '保持状态']},
        
        # 实时操作系统
        {'id': 450, 'label': 'RTOS', 'group': 'embedded', 'title': '实时操作系统', 'level': 2,
         'description': '实时操作系统(RTOS)提供任务调度、同步、通信等功能，保证任务的实时性。是复杂嵌入式系统的基础。',
         'difficulty': 3, 'learning_hours': 5},
        {'id': 451, 'label': 'FreeRTOS', 'group': 'embedded', 'title': 'FreeRTOS系统', 'level': 3,
         'description': 'FreeRTOS是开源的实时操作系统，轻量级、可裁剪，广泛应用于嵌入式系统。',
         'difficulty': 3, 'learning_hours': 5},
        {'id': 452, 'label': '任务调度', 'group': 'embedded', 'title': 'Task Scheduling', 'level': 3,
         'description': '任务调度是RTOS的核心，包括抢占式调度和协作式调度。通过优先级和时间片实现多任务并发执行。',
         'difficulty': 3, 'learning_hours': 4,
         'formulas': ['优先级调度', '时间片轮转', '调度延迟', '上下文切换时间']},
        {'id': 453, 'label': '信号量', 'group': 'embedded', 'title': 'Semaphore', 'level': 3,
         'description': '信号量用于任务间的同步和互斥，包括二进制信号量和计数信号量。是RTOS的重要同步机制。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['P操作(等待)', 'V操作(释放)', '互斥锁', '资源计数']},
        {'id': 454, 'label': '消息队列', 'group': 'embedded', 'title': 'Message Queue', 'level': 3,
         'description': '消息队列用于任务间的数据传递，支持FIFO和优先级队列。是RTOS的重要通信机制。',
         'difficulty': 3, 'learning_hours': 3,
         'formulas': ['队列长度', '消息大小', '发送/接收操作', '阻塞/非阻塞']},
    ]
    
    # 关系数据 - 内部关联和跨课程关联
    edges = []
    
    # ============ 电路基础内部关联 ============
    # 基础关系
    edges.extend([
        {'from': 1, 'to': 2, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 1, 'to': 3, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 1, 'to': 10, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 3, 'to': 2, 'label': '基于', 'color': {'color': '#FFB84D'}},
        {'from': 4, 'to': 3, 'label': '基于', 'color': {'color': '#FFB84D'}},
        {'from': 5, 'to': 3, 'label': '基于', 'color': {'color': '#FFB84D'}},
        {'from': 6, 'to': 3, 'label': '基于', 'color': {'color': '#FFB84D'}},
        {'from': 7, 'to': 4, 'label': '应用于', 'color': {'color': '#FFB84D'}},
        {'from': 7, 'to': 5, 'label': '应用于', 'color': {'color': '#FFB84D'}},
    ])
    
    # 交流电路关系
    edges.extend([
        {'from': 10, 'to': 11, 'label': '涉及', 'color': {'color': '#97C2FC'}},
        {'from': 10, 'to': 12, 'label': '涉及', 'color': {'color': '#97C2FC'}},
        {'from': 10, 'to': 13, 'label': '涉及', 'color': {'color': '#97C2FC'}},
        {'from': 10, 'to': 14, 'label': '分析方法', 'color': {'color': '#97C2FC'}},
        {'from': 10, 'to': 15, 'label': '扩展', 'color': {'color': '#97C2FC'}},
        {'from': 14, 'to': 11, 'label': '用于', 'color': {'color': '#FFB84D'}},
        {'from': 15, 'to': 16, 'label': '分析方法', 'color': {'color': '#FFB84D'}},
        {'from': 10, 'to': 17, 'label': '分析方法', 'color': {'color': '#FFB84D'}},
    ])
    
    # 动态电路关系
    edges.extend([
        {'from': 1, 'to': 20, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 1, 'to': 21, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 20, 'to': 22, 'label': '响应类型', 'color': {'color': '#FFB84D'}},
        {'from': 21, 'to': 22, 'label': '响应类型', 'color': {'color': '#FFB84D'}},
        {'from': 21, 'to': 23, 'label': '响应类型', 'color': {'color': '#FFB84D'}},
        {'from': 23, 'to': 24, 'label': '分析方法', 'color': {'color': '#FFB84D'}},
    ])
    
    # 磁路关系
    edges.extend([
        {'from': 1, 'to': 30, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 30, 'to': 31, 'label': '涉及', 'color': {'color': '#FFB84D'}},
        {'from': 31, 'to': 32, 'label': '构成', 'color': {'color': '#FFB84D'}},
        {'from': 32, 'to': 33, 'label': '扩展为', 'color': {'color': '#FFB84D'}},
        {'from': 32, 'to': 34, 'label': '变型', 'color': {'color': '#FFB84D'}},
    ])
    
    # 频域分析关系
    edges.extend([
        {'from': 1, 'to': 40, 'label': '分析方法', 'color': {'color': '#FFB84D'}},
        {'from': 40, 'to': 41, 'label': '应用于', 'color': {'color': '#FFB84D'}},
        {'from': 41, 'to': 42, 'label': '分析', 'color': {'color': '#FFB84D'}},
        {'from': 41, 'to': 43, 'label': '特征', 'color': {'color': '#FFB84D'}},
        {'from': 42, 'to': 44, 'label': '应用于', 'color': {'color': '#FFB84D'}},
    ])
    
    # 二端口网络关系
    edges.extend([
        {'from': 1, 'to': 50, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 50, 'to': 51, 'label': '参数类型', 'color': {'color': '#FFB84D'}},
        {'from': 50, 'to': 52, 'label': '应用', 'color': {'color': '#FFB84D'}},
    ])
    
    # ============ 模拟电子内部关联 ============
    edges.extend([
        {'from': 100, 'to': 101, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 100, 'to': 102, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 100, 'to': 103, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 100, 'to': 110, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 101, 'to': 104, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 101, 'to': 105, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 101, 'to': 106, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 102, 'to': 120, 'label': '构成', 'color': {'color': '#FFB84D'}},
        {'from': 103, 'to': 120, 'label': '构成', 'color': {'color': '#FFB84D'}},
        {'from': 110, 'to': 111, 'label': '应用', 'color': {'color': '#FFB84D'}},
        {'from': 110, 'to': 112, 'label': '应用', 'color': {'color': '#FFB84D'}},
        {'from': 110, 'to': 113, 'label': '应用', 'color': {'color': '#FFB84D'}},
        {'from': 110, 'to': 114, 'label': '应用', 'color': {'color': '#FFB84D'}},
        {'from': 110, 'to': 115, 'label': '应用', 'color': {'color': '#FFB84D'}},
        {'from': 120, 'to': 121, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 120, 'to': 122, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 120, 'to': 123, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 120, 'to': 124, 'label': '扩展', 'color': {'color': '#FFB84D'}},
        {'from': 120, 'to': 125, 'label': '扩展', 'color': {'color': '#FFB84D'}},
        {'from': 110, 'to': 130, 'label': '应用', 'color': {'color': '#FFB84D'}},
        {'from': 130, 'to': 131, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 130, 'to': 132, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 110, 'to': 140, 'label': '应用', 'color': {'color': '#FFB84D'}},
        {'from': 140, 'to': 141, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 140, 'to': 142, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 140, 'to': 143, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 140, 'to': 144, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 132, 'to': 150, 'label': '应用', 'color': {'color': '#FFB84D'}},
        {'from': 150, 'to': 151, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 150, 'to': 152, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 150, 'to': 153, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 101, 'to': 160, 'label': '应用', 'color': {'color': '#FFB84D'}},
        {'from': 160, 'to': 161, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 160, 'to': 162, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 160, 'to': 163, 'label': '构成', 'color': {'color': '#FFB84D'}},
        {'from': 163, 'to': 164, 'label': '配合', 'color': {'color': '#FFB84D'}},
    ])
    
    # ============ 数字电子内部关联 ============
    edges.extend([
        {'from': 200, 'to': 201, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 200, 'to': 202, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 202, 'to': 203, 'label': '应用于', 'color': {'color': '#FFB84D'}},
        {'from': 202, 'to': 204, 'label': '表示', 'color': {'color': '#FFB84D'}},
        {'from': 201, 'to': 210, 'label': '构成', 'color': {'color': '#FFB84D'}},
        {'from': 210, 'to': 211, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 210, 'to': 212, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 210, 'to': 213, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 210, 'to': 214, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 210, 'to': 215, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 210, 'to': 216, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 210, 'to': 220, 'label': '扩展为', 'color': {'color': '#FFB84D'}},
        {'from': 220, 'to': 221, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 220, 'to': 222, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 221, 'to': 223, 'label': '构成', 'color': {'color': '#FFB84D'}},
        {'from': 221, 'to': 224, 'label': '构成', 'color': {'color': '#FFB84D'}},
        {'from': 224, 'to': 225, 'label': '扩展', 'color': {'color': '#FFB84D'}},
        {'from': 221, 'to': 226, 'label': '应用', 'color': {'color': '#FFB84D'}},
        {'from': 200, 'to': 230, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 230, 'to': 231, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 230, 'to': 232, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 230, 'to': 233, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 200, 'to': 240, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 200, 'to': 241, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 240, 'to': 242, 'label': '基于', 'color': {'color': '#FFB84D'}},
        {'from': 240, 'to': 243, 'label': '涉及', 'color': {'color': '#FFB84D'}},
        {'from': 200, 'to': 250, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 250, 'to': 251, 'label': '相关', 'color': {'color': '#FFB84D'}},
        {'from': 250, 'to': 252, 'label': '使用', 'color': {'color': '#FFB84D'}},
        {'from': 252, 'to': 253, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 252, 'to': 254, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 200, 'to': 260, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 260, 'to': 261, 'label': '算法', 'color': {'color': '#FFB84D'}},
        {'from': 260, 'to': 262, 'label': '应用', 'color': {'color': '#FFB84D'}},
        {'from': 260, 'to': 263, 'label': '应用', 'color': {'color': '#FFB84D'}},
    ])
    
    # ============ 高频电子内部关联 ============
    edges.extend([
        {'from': 300, 'to': 301, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 301, 'to': 302, 'label': '参数', 'color': {'color': '#FFB84D'}},
        {'from': 301, 'to': 303, 'label': '参数', 'color': {'color': '#FFB84D'}},
        {'from': 301, 'to': 304, 'label': '扩展', 'color': {'color': '#FFB84D'}},
        {'from': 300, 'to': 310, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 310, 'to': 311, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 310, 'to': 312, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 312, 'to': 313, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 312, 'to': 314, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 300, 'to': 320, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 320, 'to': 321, 'label': '应用', 'color': {'color': '#FFB84D'}},
        {'from': 320, 'to': 322, 'label': '应用', 'color': {'color': '#FFB84D'}},
        {'from': 320, 'to': 323, 'label': '涉及', 'color': {'color': '#FFB84D'}},
        {'from': 300, 'to': 330, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 330, 'to': 331, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 330, 'to': 332, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 330, 'to': 333, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 300, 'to': 340, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 340, 'to': 341, 'label': '组成', 'color': {'color': '#FFB84D'}},
        {'from': 340, 'to': 342, 'label': '组成', 'color': {'color': '#FFB84D'}},
        {'from': 340, 'to': 343, 'label': '组成', 'color': {'color': '#FFB84D'}},
        {'from': 300, 'to': 350, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 300, 'to': 360, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 360, 'to': 361, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 300, 'to': 370, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 300, 'to': 380, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 380, 'to': 381, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 380, 'to': 382, 'label': '类型', 'color': {'color': '#FFB84D'}},
    ])
    
    # ============ 嵌入式内部关联 ============
    edges.extend([
        {'from': 400, 'to': 401, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 401, 'to': 402, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 402, 'to': 403, 'label': '系列', 'color': {'color': '#FFB84D'}},
        {'from': 402, 'to': 404, 'label': '系列', 'color': {'color': '#FFB84D'}},
        {'from': 401, 'to': 405, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 401, 'to': 406, 'label': '类型', 'color': {'color': '#FFB84D'}},
        {'from': 401, 'to': 410, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 401, 'to': 411, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 401, 'to': 412, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 401, 'to': 420, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 401, 'to': 421, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 401, 'to': 422, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 421, 'to': 422, 'label': '相关', 'color': {'color': '#FFB84D'}},
        {'from': 401, 'to': 423, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 401, 'to': 440, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 401, 'to': 441, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 400, 'to': 450, 'label': '包含', 'color': {'color': '#97C2FC'}},
        {'from': 450, 'to': 451, 'label': '实现', 'color': {'color': '#FFB84D'}},
        {'from': 450, 'to': 452, 'label': '功能', 'color': {'color': '#FFB84D'}},
        {'from': 450, 'to': 453, 'label': '机制', 'color': {'color': '#FFB84D'}},
    ])
    
    # ============ 跨课程关联 ============
    edges.extend([
        # 电路 -> 模电
        {'from': 1, 'to': 100, 'label': '基础', 'color': {'color': '#FF6B6B'}},
        {'from': 2, 'to': 101, 'label': '应用于', 'color': {'color': '#FF6B6B'}},
        {'from': 3, 'to': 120, 'label': '应用于', 'color': {'color': '#FF6B6B'}},
        {'from': 11, 'to': 141, 'label': '应用于', 'color': {'color': '#FF6B6B'}},
        {'from': 42, 'to': 127, 'label': '应用于', 'color': {'color': '#FF6B6B'}},
        {'from': 41, 'to': 126, 'label': '分析方法', 'color': {'color': '#FF6B6B'}},
        
        # 电路 -> 高频
        {'from': 10, 'to': 301, 'label': '扩展', 'color': {'color': '#FF6B6B'}},
        {'from': 11, 'to': 301, 'label': '应用于', 'color': {'color': '#FF6B6B'}},
        {'from': 14, 'to': 301, 'label': '应用于', 'color': {'color': '#FF6B6B'}},
        {'from': 42, 'to': 370, 'label': '应用于', 'color': {'color': '#FF6B6B'}},
        {'from': 50, 'to': 360, 'label': '应用于', 'color': {'color': '#FF6B6B'}},
        
        # 模电 -> 数电
        {'from': 100, 'to': 200, 'label': '基础', 'color': {'color': '#FF6B6B'}},
        {'from': 101, 'to': 201, 'label': '对应', 'color': {'color': '#FF6B6B'}},
        {'from': 110, 'to': 240, 'label': '应用于', 'color': {'color': '#FF6B6B'}},
        {'from': 110, 'to': 241, 'label': '应用于', 'color': {'color': '#FF6B6B'}},
        {'from': 141, 'to': 262, 'label': '对应', 'color': {'color': '#FF6B6B'}},
        
        # 模电 -> 高频
        {'from': 100, 'to': 300, 'label': '基础', 'color': {'color': '#FF6B6B'}},
        {'from': 120, 'to': 310, 'label': '扩展', 'color': {'color': '#FF6B6B'}},
        {'from': 125, 'to': 312, 'label': '对应', 'color': {'color': '#FF6B6B'}},
        {'from': 150, 'to': 342, 'label': '应用于', 'color': {'color': '#FF6B6B'}},
        {'from': 140, 'to': 370, 'label': '对应', 'color': {'color': '#FF6B6B'}},
        
        # 数电 -> 嵌入式
        {'from': 200, 'to': 400, 'label': '基础', 'color': {'color': '#FF6B6B'}},
        {'from': 201, 'to': 410, 'label': '应用于', 'color': {'color': '#FF6B6B'}},
        {'from': 221, 'to': 411, 'label': '实现', 'color': {'color': '#FF6B6B'}},
        {'from': 223, 'to': 412, 'label': '对应', 'color': {'color': '#FF6B6B'}},
        {'from': 230, 'to': 430, 'label': '应用于', 'color': {'color': '#FF6B6B'}},
        {'from': 240, 'to': 414, 'label': '应用于', 'color': {'color': '#FF6B6B'}},
        {'from': 241, 'to': 415, 'label': '应用于', 'color': {'color': '#FF6B6B'}},
        {'from': 226, 'to': 452, 'label': '应用于', 'color': {'color': '#FF6B6B'}},
        {'from': 250, 'to': 401, 'label': '实现', 'color': {'color': '#FF6B6B'}},
        
        # 高频 -> 嵌入式
        {'from': 330, 'to': 425, 'label': '应用于', 'color': {'color': '#FF6B6B'}},
        {'from': 330, 'to': 426, 'label': '应用于', 'color': {'color': '#FF6B6B'}},
        {'from': 330, 'to': 427, 'label': '应用于', 'color': {'color': '#FF6B6B'}},
        
        # 其他跨课程关联
        {'from': 16, 'to': 340, 'label': '应用于', 'color': {'color': '#FF6B6B'}},
        {'from': 163, 'to': 160, 'label': '构成', 'color': {'color': '#FF6B6B'}},
        {'from': 242, 'to': 240, 'label': '基于', 'color': {'color': '#FF6B6B'}},
    ])
    
    return {
        'nodes': nodes,
        'edges': edges
    }
